/*
 Navicat Premium Data Transfer

 Source Server         : lokal
 Source Server Type    : MySQL
 Source Server Version : 100408
 Source Host           : localhost:3306
 Source Schema         : db_vividi_trans

 Target Server Type    : MySQL
 Target Server Version : 100408
 File Encoding         : 65001

 Date: 27/11/2019 21:07:07
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for tb_booking
-- ----------------------------
DROP TABLE IF EXISTS `tb_booking`;
CREATE TABLE `tb_booking`  (
  `f_id_booking` int(10) NOT NULL,
  `f_kode_booking` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `f_kode_user` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'relasi dengan kode user - tb user data;',
  `f_kode_kamar` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'relasi ke kode kamar - tb kamar;',
  `f_check_in_bk` date NULL DEFAULT NULL,
  `f_check_out_bk` date NULL DEFAULT NULL,
  `f_jumlah_kamar` int(10) NULL DEFAULT NULL,
  `f_total_harga` int(10) NULL DEFAULT NULL,
  `f_tgl_booking` date NULL DEFAULT NULL,
  `f_status_booking` enum('0','1','2') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '2' COMMENT '0:gagal,1:aktif,2:menunggu;',
  PRIMARY KEY (`f_id_booking`, `f_kode_booking`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tb_detail_fasilitas
-- ----------------------------
DROP TABLE IF EXISTS `tb_detail_fasilitas`;
CREATE TABLE `tb_detail_fasilitas`  (
  `f_detail_fasilitas` int(10) NOT NULL AUTO_INCREMENT,
  `f_parent_fasilitas` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'relasi ke kode_properti,kode kamar dll yang menggunakan fasilitas;',
  `f_fasilitas` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'relasi dengan id fasilitas;',
  PRIMARY KEY (`f_detail_fasilitas`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tb_detail_harga
-- ----------------------------
DROP TABLE IF EXISTS `tb_detail_harga`;
CREATE TABLE `tb_detail_harga`  (
  `f_id_detail_harga` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tb_detail_mitra
-- ----------------------------
DROP TABLE IF EXISTS `tb_detail_mitra`;
CREATE TABLE `tb_detail_mitra`  (
  `f_id_detail_mitra` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `f_detail_properti_mitra` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_user_mitra` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`f_id_detail_mitra`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tb_detail_tour_guide
-- ----------------------------
DROP TABLE IF EXISTS `tb_detail_tour_guide`;
CREATE TABLE `tb_detail_tour_guide`  (
  `f_id_detail_tour_guide` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `f_detail_kode_tg` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'relasi kode tg di tb tour guide;',
  `f_nama_detail_tg` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_desc_tg` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `f_status_tg` enum('0','1') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '1' COMMENT '0:nonaktif;1:aktif;',
  PRIMARY KEY (`f_id_detail_tour_guide`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tb_detail_upload
-- ----------------------------
DROP TABLE IF EXISTS `tb_detail_upload`;
CREATE TABLE `tb_detail_upload`  (
  `f_detail_upload_image` int(10) NULL DEFAULT NULL,
  `f_kode_image` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'relasi ke kode image - tb_image;',
  `f_parent_image` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'relasi ke kode properti, kode kamar, kode user dll;'
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tb_fasilitas
-- ----------------------------
DROP TABLE IF EXISTS `tb_fasilitas`;
CREATE TABLE `tb_fasilitas`  (
  `f_id_fasilitas` int(10) NOT NULL AUTO_INCREMENT,
  `f_nama_fasilitas` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_tipe_fasilitas` enum('0','1','2','3','4','5') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '0 global,1 properti,2 kamar,3 umrah,4 sewa kendaraan,5 tour;',
  `f_status_fasilitas` enum('0','1') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '1',
  PRIMARY KEY (`f_id_fasilitas`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tb_harga
-- ----------------------------
DROP TABLE IF EXISTS `tb_harga`;
CREATE TABLE `tb_harga`  (
  `f_id_harga` int(10) NOT NULL,
  `f_kode_properti` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'relasi ke kode properti - tb properti;',
  `f_kode_kamar` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'relasi ke kode kamar - tb kamar;',
  `f_harga_awal` int(10) NULL DEFAULT NULL,
  `f_harga_akhir` int(10) NULL DEFAULT NULL,
  `f_tanggal_awal` date NULL DEFAULT NULL,
  `f_tanggal_akhir` date NULL DEFAULT NULL,
  `f_allotment` int(10) NULL DEFAULT NULL,
  `f_diskon_harga` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`f_id_harga`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tb_image
-- ----------------------------
DROP TABLE IF EXISTS `tb_image`;
CREATE TABLE `tb_image`  (
  `f_id_image` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `f_image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_title_image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_desc_image` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `f_tag_image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'relasi ke id tag images - tb tags image;',
  PRIMARY KEY (`f_id_image`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tb_kamar
-- ----------------------------
DROP TABLE IF EXISTS `tb_kamar`;
CREATE TABLE `tb_kamar`  (
  `f_id_kamar` int(10) NOT NULL,
  `f_kode_kamar` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `f_kode_properti` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'relasi ke kode properti tb properti;',
  `f_nama_kamar` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_desc_kamar` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `f_max_adult` int(10) NULL DEFAULT NULL,
  `f_max_child` int(10) NULL DEFAULT NULL,
  `f_status_kamar` enum('0','1') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '1' COMMENT '0:nonaktif;1:aktif;',
  PRIMARY KEY (`f_id_kamar`, `f_kode_kamar`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tb_kendaraan
-- ----------------------------
DROP TABLE IF EXISTS `tb_kendaraan`;
CREATE TABLE `tb_kendaraan`  (
  `f_id_kendaraan` int(10) NOT NULL,
  `f_kode_kendaraan` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`f_id_kendaraan`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tb_kota
-- ----------------------------
DROP TABLE IF EXISTS `tb_kota`;
CREATE TABLE `tb_kota`  (
  `f_id_kota` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `f_provinsi` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_nama_kota` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`f_id_kota`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tb_kota
-- ----------------------------
INSERT INTO `tb_kota` VALUES ('1101', '11', 'KABUPATEN SIMEULUE');
INSERT INTO `tb_kota` VALUES ('1102', '11', 'KABUPATEN ACEH SINGKIL');
INSERT INTO `tb_kota` VALUES ('1103', '11', 'KABUPATEN ACEH SELATAN');
INSERT INTO `tb_kota` VALUES ('1104', '11', 'KABUPATEN ACEH TENGGARA');
INSERT INTO `tb_kota` VALUES ('1105', '11', 'KABUPATEN ACEH TIMUR');
INSERT INTO `tb_kota` VALUES ('1106', '11', 'KABUPATEN ACEH TENGAH');
INSERT INTO `tb_kota` VALUES ('1107', '11', 'KABUPATEN ACEH BARAT');
INSERT INTO `tb_kota` VALUES ('1108', '11', 'KABUPATEN ACEH BESAR');
INSERT INTO `tb_kota` VALUES ('1109', '11', 'KABUPATEN PIDIE');
INSERT INTO `tb_kota` VALUES ('1110', '11', 'KABUPATEN BIREUEN');
INSERT INTO `tb_kota` VALUES ('1111', '11', 'KABUPATEN ACEH UTARA');
INSERT INTO `tb_kota` VALUES ('1112', '11', 'KABUPATEN ACEH BARAT DAYA');
INSERT INTO `tb_kota` VALUES ('1113', '11', 'KABUPATEN GAYO LUES');
INSERT INTO `tb_kota` VALUES ('1114', '11', 'KABUPATEN ACEH TAMIANG');
INSERT INTO `tb_kota` VALUES ('1115', '11', 'KABUPATEN NAGAN RAYA');
INSERT INTO `tb_kota` VALUES ('1116', '11', 'KABUPATEN ACEH JAYA');
INSERT INTO `tb_kota` VALUES ('1117', '11', 'KABUPATEN BENER MERIAH');
INSERT INTO `tb_kota` VALUES ('1118', '11', 'KABUPATEN PIDIE JAYA');
INSERT INTO `tb_kota` VALUES ('1171', '11', 'KOTA BANDA ACEH');
INSERT INTO `tb_kota` VALUES ('1172', '11', 'KOTA SABANG');
INSERT INTO `tb_kota` VALUES ('1173', '11', 'KOTA LANGSA');
INSERT INTO `tb_kota` VALUES ('1174', '11', 'KOTA LHOKSEUMAWE');
INSERT INTO `tb_kota` VALUES ('1175', '11', 'KOTA SUBULUSSALAM');
INSERT INTO `tb_kota` VALUES ('1201', '12', 'KABUPATEN NIAS');
INSERT INTO `tb_kota` VALUES ('1202', '12', 'KABUPATEN MANDAILING NATAL');
INSERT INTO `tb_kota` VALUES ('1203', '12', 'KABUPATEN TAPANULI SELATAN');
INSERT INTO `tb_kota` VALUES ('1204', '12', 'KABUPATEN TAPANULI TENGAH');
INSERT INTO `tb_kota` VALUES ('1205', '12', 'KABUPATEN TAPANULI UTARA');
INSERT INTO `tb_kota` VALUES ('1206', '12', 'KABUPATEN TOBA SAMOSIR');
INSERT INTO `tb_kota` VALUES ('1207', '12', 'KABUPATEN LABUHAN BATU');
INSERT INTO `tb_kota` VALUES ('1208', '12', 'KABUPATEN ASAHAN');
INSERT INTO `tb_kota` VALUES ('1209', '12', 'KABUPATEN SIMALUNGUN');
INSERT INTO `tb_kota` VALUES ('1210', '12', 'KABUPATEN DAIRI');
INSERT INTO `tb_kota` VALUES ('1211', '12', 'KABUPATEN KARO');
INSERT INTO `tb_kota` VALUES ('1212', '12', 'KABUPATEN DELI SERDANG');
INSERT INTO `tb_kota` VALUES ('1213', '12', 'KABUPATEN LANGKAT');
INSERT INTO `tb_kota` VALUES ('1214', '12', 'KABUPATEN NIAS SELATAN');
INSERT INTO `tb_kota` VALUES ('1215', '12', 'KABUPATEN HUMBANG HASUNDUTAN');
INSERT INTO `tb_kota` VALUES ('1216', '12', 'KABUPATEN PAKPAK BHARAT');
INSERT INTO `tb_kota` VALUES ('1217', '12', 'KABUPATEN SAMOSIR');
INSERT INTO `tb_kota` VALUES ('1218', '12', 'KABUPATEN SERDANG BEDAGAI');
INSERT INTO `tb_kota` VALUES ('1219', '12', 'KABUPATEN BATU BARA');
INSERT INTO `tb_kota` VALUES ('1220', '12', 'KABUPATEN PADANG LAWAS UTARA');
INSERT INTO `tb_kota` VALUES ('1221', '12', 'KABUPATEN PADANG LAWAS');
INSERT INTO `tb_kota` VALUES ('1222', '12', 'KABUPATEN LABUHAN BATU SELATAN');
INSERT INTO `tb_kota` VALUES ('1223', '12', 'KABUPATEN LABUHAN BATU UTARA');
INSERT INTO `tb_kota` VALUES ('1224', '12', 'KABUPATEN NIAS UTARA');
INSERT INTO `tb_kota` VALUES ('1225', '12', 'KABUPATEN NIAS BARAT');
INSERT INTO `tb_kota` VALUES ('1271', '12', 'KOTA SIBOLGA');
INSERT INTO `tb_kota` VALUES ('1272', '12', 'KOTA TANJUNG BALAI');
INSERT INTO `tb_kota` VALUES ('1273', '12', 'KOTA PEMATANG SIANTAR');
INSERT INTO `tb_kota` VALUES ('1274', '12', 'KOTA TEBING TINGGI');
INSERT INTO `tb_kota` VALUES ('1275', '12', 'KOTA MEDAN');
INSERT INTO `tb_kota` VALUES ('1276', '12', 'KOTA BINJAI');
INSERT INTO `tb_kota` VALUES ('1277', '12', 'KOTA PADANGSIDIMPUAN');
INSERT INTO `tb_kota` VALUES ('1278', '12', 'KOTA GUNUNGSITOLI');
INSERT INTO `tb_kota` VALUES ('1301', '13', 'KABUPATEN KEPULAUAN MENTAWAI');
INSERT INTO `tb_kota` VALUES ('1302', '13', 'KABUPATEN PESISIR SELATAN');
INSERT INTO `tb_kota` VALUES ('1303', '13', 'KABUPATEN SOLOK');
INSERT INTO `tb_kota` VALUES ('1304', '13', 'KABUPATEN SIJUNJUNG');
INSERT INTO `tb_kota` VALUES ('1305', '13', 'KABUPATEN TANAH DATAR');
INSERT INTO `tb_kota` VALUES ('1306', '13', 'KABUPATEN PADANG PARIAMAN');
INSERT INTO `tb_kota` VALUES ('1307', '13', 'KABUPATEN AGAM');
INSERT INTO `tb_kota` VALUES ('1308', '13', 'KABUPATEN LIMA PULUH KOTA');
INSERT INTO `tb_kota` VALUES ('1309', '13', 'KABUPATEN PASAMAN');
INSERT INTO `tb_kota` VALUES ('1310', '13', 'KABUPATEN SOLOK SELATAN');
INSERT INTO `tb_kota` VALUES ('1311', '13', 'KABUPATEN DHARMASRAYA');
INSERT INTO `tb_kota` VALUES ('1312', '13', 'KABUPATEN PASAMAN BARAT');
INSERT INTO `tb_kota` VALUES ('1371', '13', 'KOTA PADANG');
INSERT INTO `tb_kota` VALUES ('1372', '13', 'KOTA SOLOK');
INSERT INTO `tb_kota` VALUES ('1373', '13', 'KOTA SAWAH LUNTO');
INSERT INTO `tb_kota` VALUES ('1374', '13', 'KOTA PADANG PANJANG');
INSERT INTO `tb_kota` VALUES ('1375', '13', 'KOTA BUKITTINGGI');
INSERT INTO `tb_kota` VALUES ('1376', '13', 'KOTA PAYAKUMBUH');
INSERT INTO `tb_kota` VALUES ('1377', '13', 'KOTA PARIAMAN');
INSERT INTO `tb_kota` VALUES ('1401', '14', 'KABUPATEN KUANTAN SINGINGI');
INSERT INTO `tb_kota` VALUES ('1402', '14', 'KABUPATEN INDRAGIRI HULU');
INSERT INTO `tb_kota` VALUES ('1403', '14', 'KABUPATEN INDRAGIRI HILIR');
INSERT INTO `tb_kota` VALUES ('1404', '14', 'KABUPATEN PELALAWAN');
INSERT INTO `tb_kota` VALUES ('1405', '14', 'KABUPATEN S I A K');
INSERT INTO `tb_kota` VALUES ('1406', '14', 'KABUPATEN KAMPAR');
INSERT INTO `tb_kota` VALUES ('1407', '14', 'KABUPATEN ROKAN HULU');
INSERT INTO `tb_kota` VALUES ('1408', '14', 'KABUPATEN BENGKALIS');
INSERT INTO `tb_kota` VALUES ('1409', '14', 'KABUPATEN ROKAN HILIR');
INSERT INTO `tb_kota` VALUES ('1410', '14', 'KABUPATEN KEPULAUAN MERANTI');
INSERT INTO `tb_kota` VALUES ('1471', '14', 'KOTA PEKANBARU');
INSERT INTO `tb_kota` VALUES ('1473', '14', 'KOTA D U M A I');
INSERT INTO `tb_kota` VALUES ('1501', '15', 'KABUPATEN KERINCI');
INSERT INTO `tb_kota` VALUES ('1502', '15', 'KABUPATEN MERANGIN');
INSERT INTO `tb_kota` VALUES ('1503', '15', 'KABUPATEN SAROLANGUN');
INSERT INTO `tb_kota` VALUES ('1504', '15', 'KABUPATEN BATANG HARI');
INSERT INTO `tb_kota` VALUES ('1505', '15', 'KABUPATEN MUARO JAMBI');
INSERT INTO `tb_kota` VALUES ('1506', '15', 'KABUPATEN TANJUNG JABUNG TIMUR');
INSERT INTO `tb_kota` VALUES ('1507', '15', 'KABUPATEN TANJUNG JABUNG BARAT');
INSERT INTO `tb_kota` VALUES ('1508', '15', 'KABUPATEN TEBO');
INSERT INTO `tb_kota` VALUES ('1509', '15', 'KABUPATEN BUNGO');
INSERT INTO `tb_kota` VALUES ('1571', '15', 'KOTA JAMBI');
INSERT INTO `tb_kota` VALUES ('1572', '15', 'KOTA SUNGAI PENUH');
INSERT INTO `tb_kota` VALUES ('1601', '16', 'KABUPATEN OGAN KOMERING ULU');
INSERT INTO `tb_kota` VALUES ('1602', '16', 'KABUPATEN OGAN KOMERING ILIR');
INSERT INTO `tb_kota` VALUES ('1603', '16', 'KABUPATEN MUARA ENIM');
INSERT INTO `tb_kota` VALUES ('1604', '16', 'KABUPATEN LAHAT');
INSERT INTO `tb_kota` VALUES ('1605', '16', 'KABUPATEN MUSI RAWAS');
INSERT INTO `tb_kota` VALUES ('1606', '16', 'KABUPATEN MUSI BANYUASIN');
INSERT INTO `tb_kota` VALUES ('1607', '16', 'KABUPATEN BANYU ASIN');
INSERT INTO `tb_kota` VALUES ('1608', '16', 'KABUPATEN OGAN KOMERING ULU SELATAN');
INSERT INTO `tb_kota` VALUES ('1609', '16', 'KABUPATEN OGAN KOMERING ULU TIMUR');
INSERT INTO `tb_kota` VALUES ('1610', '16', 'KABUPATEN OGAN ILIR');
INSERT INTO `tb_kota` VALUES ('1611', '16', 'KABUPATEN EMPAT LAWANG');
INSERT INTO `tb_kota` VALUES ('1612', '16', 'KABUPATEN PENUKAL ABAB LEMATANG ILIR');
INSERT INTO `tb_kota` VALUES ('1613', '16', 'KABUPATEN MUSI RAWAS UTARA');
INSERT INTO `tb_kota` VALUES ('1671', '16', 'KOTA PALEMBANG');
INSERT INTO `tb_kota` VALUES ('1672', '16', 'KOTA PRABUMULIH');
INSERT INTO `tb_kota` VALUES ('1673', '16', 'KOTA PAGAR ALAM');
INSERT INTO `tb_kota` VALUES ('1674', '16', 'KOTA LUBUKLINGGAU');
INSERT INTO `tb_kota` VALUES ('1701', '17', 'KABUPATEN BENGKULU SELATAN');
INSERT INTO `tb_kota` VALUES ('1702', '17', 'KABUPATEN REJANG LEBONG');
INSERT INTO `tb_kota` VALUES ('1703', '17', 'KABUPATEN BENGKULU UTARA');
INSERT INTO `tb_kota` VALUES ('1704', '17', 'KABUPATEN KAUR');
INSERT INTO `tb_kota` VALUES ('1705', '17', 'KABUPATEN SELUMA');
INSERT INTO `tb_kota` VALUES ('1706', '17', 'KABUPATEN MUKOMUKO');
INSERT INTO `tb_kota` VALUES ('1707', '17', 'KABUPATEN LEBONG');
INSERT INTO `tb_kota` VALUES ('1708', '17', 'KABUPATEN KEPAHIANG');
INSERT INTO `tb_kota` VALUES ('1709', '17', 'KABUPATEN BENGKULU TENGAH');
INSERT INTO `tb_kota` VALUES ('1771', '17', 'KOTA BENGKULU');
INSERT INTO `tb_kota` VALUES ('1801', '18', 'KABUPATEN LAMPUNG BARAT');
INSERT INTO `tb_kota` VALUES ('1802', '18', 'KABUPATEN TANGGAMUS');
INSERT INTO `tb_kota` VALUES ('1803', '18', 'KABUPATEN LAMPUNG SELATAN');
INSERT INTO `tb_kota` VALUES ('1804', '18', 'KABUPATEN LAMPUNG TIMUR');
INSERT INTO `tb_kota` VALUES ('1805', '18', 'KABUPATEN LAMPUNG TENGAH');
INSERT INTO `tb_kota` VALUES ('1806', '18', 'KABUPATEN LAMPUNG UTARA');
INSERT INTO `tb_kota` VALUES ('1807', '18', 'KABUPATEN WAY KANAN');
INSERT INTO `tb_kota` VALUES ('1808', '18', 'KABUPATEN TULANGBAWANG');
INSERT INTO `tb_kota` VALUES ('1809', '18', 'KABUPATEN PESAWARAN');
INSERT INTO `tb_kota` VALUES ('1810', '18', 'KABUPATEN PRINGSEWU');
INSERT INTO `tb_kota` VALUES ('1811', '18', 'KABUPATEN MESUJI');
INSERT INTO `tb_kota` VALUES ('1812', '18', 'KABUPATEN TULANG BAWANG BARAT');
INSERT INTO `tb_kota` VALUES ('1813', '18', 'KABUPATEN PESISIR BARAT');
INSERT INTO `tb_kota` VALUES ('1871', '18', 'KOTA BANDAR LAMPUNG');
INSERT INTO `tb_kota` VALUES ('1872', '18', 'KOTA METRO');
INSERT INTO `tb_kota` VALUES ('1901', '19', 'KABUPATEN BANGKA');
INSERT INTO `tb_kota` VALUES ('1902', '19', 'KABUPATEN BELITUNG');
INSERT INTO `tb_kota` VALUES ('1903', '19', 'KABUPATEN BANGKA BARAT');
INSERT INTO `tb_kota` VALUES ('1904', '19', 'KABUPATEN BANGKA TENGAH');
INSERT INTO `tb_kota` VALUES ('1905', '19', 'KABUPATEN BANGKA SELATAN');
INSERT INTO `tb_kota` VALUES ('1906', '19', 'KABUPATEN BELITUNG TIMUR');
INSERT INTO `tb_kota` VALUES ('1971', '19', 'KOTA PANGKAL PINANG');
INSERT INTO `tb_kota` VALUES ('2101', '21', 'KABUPATEN KARIMUN');
INSERT INTO `tb_kota` VALUES ('2102', '21', 'KABUPATEN BINTAN');
INSERT INTO `tb_kota` VALUES ('2103', '21', 'KABUPATEN NATUNA');
INSERT INTO `tb_kota` VALUES ('2104', '21', 'KABUPATEN LINGGA');
INSERT INTO `tb_kota` VALUES ('2105', '21', 'KABUPATEN KEPULAUAN ANAMBAS');
INSERT INTO `tb_kota` VALUES ('2171', '21', 'KOTA B A T A M');
INSERT INTO `tb_kota` VALUES ('2172', '21', 'KOTA TANJUNG PINANG');
INSERT INTO `tb_kota` VALUES ('3101', '31', 'KABUPATEN KEPULAUAN SERIBU');
INSERT INTO `tb_kota` VALUES ('3171', '31', 'KOTA JAKARTA SELATAN');
INSERT INTO `tb_kota` VALUES ('3172', '31', 'KOTA JAKARTA TIMUR');
INSERT INTO `tb_kota` VALUES ('3173', '31', 'KOTA JAKARTA PUSAT');
INSERT INTO `tb_kota` VALUES ('3174', '31', 'KOTA JAKARTA BARAT');
INSERT INTO `tb_kota` VALUES ('3175', '31', 'KOTA JAKARTA UTARA');
INSERT INTO `tb_kota` VALUES ('3201', '32', 'KABUPATEN BOGOR');
INSERT INTO `tb_kota` VALUES ('3202', '32', 'KABUPATEN SUKABUMI');
INSERT INTO `tb_kota` VALUES ('3203', '32', 'KABUPATEN CIANJUR');
INSERT INTO `tb_kota` VALUES ('3204', '32', 'KABUPATEN BANDUNG');
INSERT INTO `tb_kota` VALUES ('3205', '32', 'KABUPATEN GARUT');
INSERT INTO `tb_kota` VALUES ('3206', '32', 'KABUPATEN TASIKMALAYA');
INSERT INTO `tb_kota` VALUES ('3207', '32', 'KABUPATEN CIAMIS');
INSERT INTO `tb_kota` VALUES ('3208', '32', 'KABUPATEN KUNINGAN');
INSERT INTO `tb_kota` VALUES ('3209', '32', 'KABUPATEN CIREBON');
INSERT INTO `tb_kota` VALUES ('3210', '32', 'KABUPATEN MAJALENGKA');
INSERT INTO `tb_kota` VALUES ('3211', '32', 'KABUPATEN SUMEDANG');
INSERT INTO `tb_kota` VALUES ('3212', '32', 'KABUPATEN INDRAMAYU');
INSERT INTO `tb_kota` VALUES ('3213', '32', 'KABUPATEN SUBANG');
INSERT INTO `tb_kota` VALUES ('3214', '32', 'KABUPATEN PURWAKARTA');
INSERT INTO `tb_kota` VALUES ('3215', '32', 'KABUPATEN KARAWANG');
INSERT INTO `tb_kota` VALUES ('3216', '32', 'KABUPATEN BEKASI');
INSERT INTO `tb_kota` VALUES ('3217', '32', 'KABUPATEN BANDUNG BARAT');
INSERT INTO `tb_kota` VALUES ('3218', '32', 'KABUPATEN PANGANDARAN');
INSERT INTO `tb_kota` VALUES ('3271', '32', 'KOTA BOGOR');
INSERT INTO `tb_kota` VALUES ('3272', '32', 'KOTA SUKABUMI');
INSERT INTO `tb_kota` VALUES ('3273', '32', 'KOTA BANDUNG');
INSERT INTO `tb_kota` VALUES ('3274', '32', 'KOTA CIREBON');
INSERT INTO `tb_kota` VALUES ('3275', '32', 'KOTA BEKASI');
INSERT INTO `tb_kota` VALUES ('3276', '32', 'KOTA DEPOK');
INSERT INTO `tb_kota` VALUES ('3277', '32', 'KOTA CIMAHI');
INSERT INTO `tb_kota` VALUES ('3278', '32', 'KOTA TASIKMALAYA');
INSERT INTO `tb_kota` VALUES ('3279', '32', 'KOTA BANJAR');
INSERT INTO `tb_kota` VALUES ('3301', '33', 'KABUPATEN CILACAP');
INSERT INTO `tb_kota` VALUES ('3302', '33', 'KABUPATEN BANYUMAS');
INSERT INTO `tb_kota` VALUES ('3303', '33', 'KABUPATEN PURBALINGGA');
INSERT INTO `tb_kota` VALUES ('3304', '33', 'KABUPATEN BANJARNEGARA');
INSERT INTO `tb_kota` VALUES ('3305', '33', 'KABUPATEN KEBUMEN');
INSERT INTO `tb_kota` VALUES ('3306', '33', 'KABUPATEN PURWOREJO');
INSERT INTO `tb_kota` VALUES ('3307', '33', 'KABUPATEN WONOSOBO');
INSERT INTO `tb_kota` VALUES ('3308', '33', 'KABUPATEN MAGELANG');
INSERT INTO `tb_kota` VALUES ('3309', '33', 'KABUPATEN BOYOLALI');
INSERT INTO `tb_kota` VALUES ('3310', '33', 'KABUPATEN KLATEN');
INSERT INTO `tb_kota` VALUES ('3311', '33', 'KABUPATEN SUKOHARJO');
INSERT INTO `tb_kota` VALUES ('3312', '33', 'KABUPATEN WONOGIRI');
INSERT INTO `tb_kota` VALUES ('3313', '33', 'KABUPATEN KARANGANYAR');
INSERT INTO `tb_kota` VALUES ('3314', '33', 'KABUPATEN SRAGEN');
INSERT INTO `tb_kota` VALUES ('3315', '33', 'KABUPATEN GROBOGAN');
INSERT INTO `tb_kota` VALUES ('3316', '33', 'KABUPATEN BLORA');
INSERT INTO `tb_kota` VALUES ('3317', '33', 'KABUPATEN REMBANG');
INSERT INTO `tb_kota` VALUES ('3318', '33', 'KABUPATEN PATI');
INSERT INTO `tb_kota` VALUES ('3319', '33', 'KABUPATEN KUDUS');
INSERT INTO `tb_kota` VALUES ('3320', '33', 'KABUPATEN JEPARA');
INSERT INTO `tb_kota` VALUES ('3321', '33', 'KABUPATEN DEMAK');
INSERT INTO `tb_kota` VALUES ('3322', '33', 'KABUPATEN SEMARANG');
INSERT INTO `tb_kota` VALUES ('3323', '33', 'KABUPATEN TEMANGGUNG');
INSERT INTO `tb_kota` VALUES ('3324', '33', 'KABUPATEN KENDAL');
INSERT INTO `tb_kota` VALUES ('3325', '33', 'KABUPATEN BATANG');
INSERT INTO `tb_kota` VALUES ('3326', '33', 'KABUPATEN PEKALONGAN');
INSERT INTO `tb_kota` VALUES ('3327', '33', 'KABUPATEN PEMALANG');
INSERT INTO `tb_kota` VALUES ('3328', '33', 'KABUPATEN TEGAL');
INSERT INTO `tb_kota` VALUES ('3329', '33', 'KABUPATEN BREBES');
INSERT INTO `tb_kota` VALUES ('3371', '33', 'KOTA MAGELANG');
INSERT INTO `tb_kota` VALUES ('3372', '33', 'KOTA SURAKARTA');
INSERT INTO `tb_kota` VALUES ('3373', '33', 'KOTA SALATIGA');
INSERT INTO `tb_kota` VALUES ('3374', '33', 'KOTA SEMARANG');
INSERT INTO `tb_kota` VALUES ('3375', '33', 'KOTA PEKALONGAN');
INSERT INTO `tb_kota` VALUES ('3376', '33', 'KOTA TEGAL');
INSERT INTO `tb_kota` VALUES ('3401', '34', 'KABUPATEN KULON PROGO');
INSERT INTO `tb_kota` VALUES ('3402', '34', 'KABUPATEN BANTUL');
INSERT INTO `tb_kota` VALUES ('3403', '34', 'KABUPATEN GUNUNG KIDUL');
INSERT INTO `tb_kota` VALUES ('3404', '34', 'KABUPATEN SLEMAN');
INSERT INTO `tb_kota` VALUES ('3471', '34', 'KOTA YOGYAKARTA');
INSERT INTO `tb_kota` VALUES ('3501', '35', 'KABUPATEN PACITAN');
INSERT INTO `tb_kota` VALUES ('3502', '35', 'KABUPATEN PONOROGO');
INSERT INTO `tb_kota` VALUES ('3503', '35', 'KABUPATEN TRENGGALEK');
INSERT INTO `tb_kota` VALUES ('3504', '35', 'KABUPATEN TULUNGAGUNG');
INSERT INTO `tb_kota` VALUES ('3505', '35', 'KABUPATEN BLITAR');
INSERT INTO `tb_kota` VALUES ('3506', '35', 'KABUPATEN KEDIRI');
INSERT INTO `tb_kota` VALUES ('3507', '35', 'KABUPATEN MALANG');
INSERT INTO `tb_kota` VALUES ('3508', '35', 'KABUPATEN LUMAJANG');
INSERT INTO `tb_kota` VALUES ('3509', '35', 'KABUPATEN JEMBER');
INSERT INTO `tb_kota` VALUES ('3510', '35', 'KABUPATEN BANYUWANGI');
INSERT INTO `tb_kota` VALUES ('3511', '35', 'KABUPATEN BONDOWOSO');
INSERT INTO `tb_kota` VALUES ('3512', '35', 'KABUPATEN SITUBONDO');
INSERT INTO `tb_kota` VALUES ('3513', '35', 'KABUPATEN PROBOLINGGO');
INSERT INTO `tb_kota` VALUES ('3514', '35', 'KABUPATEN PASURUAN');
INSERT INTO `tb_kota` VALUES ('3515', '35', 'KABUPATEN SIDOARJO');
INSERT INTO `tb_kota` VALUES ('3516', '35', 'KABUPATEN MOJOKERTO');
INSERT INTO `tb_kota` VALUES ('3517', '35', 'KABUPATEN JOMBANG');
INSERT INTO `tb_kota` VALUES ('3518', '35', 'KABUPATEN NGANJUK');
INSERT INTO `tb_kota` VALUES ('3519', '35', 'KABUPATEN MADIUN');
INSERT INTO `tb_kota` VALUES ('3520', '35', 'KABUPATEN MAGETAN');
INSERT INTO `tb_kota` VALUES ('3521', '35', 'KABUPATEN NGAWI');
INSERT INTO `tb_kota` VALUES ('3522', '35', 'KABUPATEN BOJONEGORO');
INSERT INTO `tb_kota` VALUES ('3523', '35', 'KABUPATEN TUBAN');
INSERT INTO `tb_kota` VALUES ('3524', '35', 'KABUPATEN LAMONGAN');
INSERT INTO `tb_kota` VALUES ('3525', '35', 'KABUPATEN GRESIK');
INSERT INTO `tb_kota` VALUES ('3526', '35', 'KABUPATEN BANGKALAN');
INSERT INTO `tb_kota` VALUES ('3527', '35', 'KABUPATEN SAMPANG');
INSERT INTO `tb_kota` VALUES ('3528', '35', 'KABUPATEN PAMEKASAN');
INSERT INTO `tb_kota` VALUES ('3529', '35', 'KABUPATEN SUMENEP');
INSERT INTO `tb_kota` VALUES ('3571', '35', 'KOTA KEDIRI');
INSERT INTO `tb_kota` VALUES ('3572', '35', 'KOTA BLITAR');
INSERT INTO `tb_kota` VALUES ('3573', '35', 'KOTA MALANG');
INSERT INTO `tb_kota` VALUES ('3574', '35', 'KOTA PROBOLINGGO');
INSERT INTO `tb_kota` VALUES ('3575', '35', 'KOTA PASURUAN');
INSERT INTO `tb_kota` VALUES ('3576', '35', 'KOTA MOJOKERTO');
INSERT INTO `tb_kota` VALUES ('3577', '35', 'KOTA MADIUN');
INSERT INTO `tb_kota` VALUES ('3578', '35', 'KOTA SURABAYA');
INSERT INTO `tb_kota` VALUES ('3579', '35', 'KOTA BATU');
INSERT INTO `tb_kota` VALUES ('3601', '36', 'KABUPATEN PANDEGLANG');
INSERT INTO `tb_kota` VALUES ('3602', '36', 'KABUPATEN LEBAK');
INSERT INTO `tb_kota` VALUES ('3603', '36', 'KABUPATEN TANGERANG');
INSERT INTO `tb_kota` VALUES ('3604', '36', 'KABUPATEN SERANG');
INSERT INTO `tb_kota` VALUES ('3671', '36', 'KOTA TANGERANG');
INSERT INTO `tb_kota` VALUES ('3672', '36', 'KOTA CILEGON');
INSERT INTO `tb_kota` VALUES ('3673', '36', 'KOTA SERANG');
INSERT INTO `tb_kota` VALUES ('3674', '36', 'KOTA TANGERANG SELATAN');
INSERT INTO `tb_kota` VALUES ('5101', '51', 'KABUPATEN JEMBRANA');
INSERT INTO `tb_kota` VALUES ('5102', '51', 'KABUPATEN TABANAN');
INSERT INTO `tb_kota` VALUES ('5103', '51', 'KABUPATEN BADUNG');
INSERT INTO `tb_kota` VALUES ('5104', '51', 'KABUPATEN GIANYAR');
INSERT INTO `tb_kota` VALUES ('5105', '51', 'KABUPATEN KLUNGKUNG');
INSERT INTO `tb_kota` VALUES ('5106', '51', 'KABUPATEN BANGLI');
INSERT INTO `tb_kota` VALUES ('5107', '51', 'KABUPATEN KARANG ASEM');
INSERT INTO `tb_kota` VALUES ('5108', '51', 'KABUPATEN BULELENG');
INSERT INTO `tb_kota` VALUES ('5171', '51', 'KOTA DENPASAR');
INSERT INTO `tb_kota` VALUES ('5201', '52', 'KABUPATEN LOMBOK BARAT');
INSERT INTO `tb_kota` VALUES ('5202', '52', 'KABUPATEN LOMBOK TENGAH');
INSERT INTO `tb_kota` VALUES ('5203', '52', 'KABUPATEN LOMBOK TIMUR');
INSERT INTO `tb_kota` VALUES ('5204', '52', 'KABUPATEN SUMBAWA');
INSERT INTO `tb_kota` VALUES ('5205', '52', 'KABUPATEN DOMPU');
INSERT INTO `tb_kota` VALUES ('5206', '52', 'KABUPATEN BIMA');
INSERT INTO `tb_kota` VALUES ('5207', '52', 'KABUPATEN SUMBAWA BARAT');
INSERT INTO `tb_kota` VALUES ('5208', '52', 'KABUPATEN LOMBOK UTARA');
INSERT INTO `tb_kota` VALUES ('5271', '52', 'KOTA MATARAM');
INSERT INTO `tb_kota` VALUES ('5272', '52', 'KOTA BIMA');
INSERT INTO `tb_kota` VALUES ('5301', '53', 'KABUPATEN SUMBA BARAT');
INSERT INTO `tb_kota` VALUES ('5302', '53', 'KABUPATEN SUMBA TIMUR');
INSERT INTO `tb_kota` VALUES ('5303', '53', 'KABUPATEN KUPANG');
INSERT INTO `tb_kota` VALUES ('5304', '53', 'KABUPATEN TIMOR TENGAH SELATAN');
INSERT INTO `tb_kota` VALUES ('5305', '53', 'KABUPATEN TIMOR TENGAH UTARA');
INSERT INTO `tb_kota` VALUES ('5306', '53', 'KABUPATEN BELU');
INSERT INTO `tb_kota` VALUES ('5307', '53', 'KABUPATEN ALOR');
INSERT INTO `tb_kota` VALUES ('5308', '53', 'KABUPATEN LEMBATA');
INSERT INTO `tb_kota` VALUES ('5309', '53', 'KABUPATEN FLORES TIMUR');
INSERT INTO `tb_kota` VALUES ('5310', '53', 'KABUPATEN SIKKA');
INSERT INTO `tb_kota` VALUES ('5311', '53', 'KABUPATEN ENDE');
INSERT INTO `tb_kota` VALUES ('5312', '53', 'KABUPATEN NGADA');
INSERT INTO `tb_kota` VALUES ('5313', '53', 'KABUPATEN MANGGARAI');
INSERT INTO `tb_kota` VALUES ('5314', '53', 'KABUPATEN ROTE NDAO');
INSERT INTO `tb_kota` VALUES ('5315', '53', 'KABUPATEN MANGGARAI BARAT');
INSERT INTO `tb_kota` VALUES ('5316', '53', 'KABUPATEN SUMBA TENGAH');
INSERT INTO `tb_kota` VALUES ('5317', '53', 'KABUPATEN SUMBA BARAT DAYA');
INSERT INTO `tb_kota` VALUES ('5318', '53', 'KABUPATEN NAGEKEO');
INSERT INTO `tb_kota` VALUES ('5319', '53', 'KABUPATEN MANGGARAI TIMUR');
INSERT INTO `tb_kota` VALUES ('5320', '53', 'KABUPATEN SABU RAIJUA');
INSERT INTO `tb_kota` VALUES ('5321', '53', 'KABUPATEN MALAKA');
INSERT INTO `tb_kota` VALUES ('5371', '53', 'KOTA KUPANG');
INSERT INTO `tb_kota` VALUES ('6101', '61', 'KABUPATEN SAMBAS');
INSERT INTO `tb_kota` VALUES ('6102', '61', 'KABUPATEN BENGKAYANG');
INSERT INTO `tb_kota` VALUES ('6103', '61', 'KABUPATEN LANDAK');
INSERT INTO `tb_kota` VALUES ('6104', '61', 'KABUPATEN MEMPAWAH');
INSERT INTO `tb_kota` VALUES ('6105', '61', 'KABUPATEN SANGGAU');
INSERT INTO `tb_kota` VALUES ('6106', '61', 'KABUPATEN KETAPANG');
INSERT INTO `tb_kota` VALUES ('6107', '61', 'KABUPATEN SINTANG');
INSERT INTO `tb_kota` VALUES ('6108', '61', 'KABUPATEN KAPUAS HULU');
INSERT INTO `tb_kota` VALUES ('6109', '61', 'KABUPATEN SEKADAU');
INSERT INTO `tb_kota` VALUES ('6110', '61', 'KABUPATEN MELAWI');
INSERT INTO `tb_kota` VALUES ('6111', '61', 'KABUPATEN KAYONG UTARA');
INSERT INTO `tb_kota` VALUES ('6112', '61', 'KABUPATEN KUBU RAYA');
INSERT INTO `tb_kota` VALUES ('6171', '61', 'KOTA PONTIANAK');
INSERT INTO `tb_kota` VALUES ('6172', '61', 'KOTA SINGKAWANG');
INSERT INTO `tb_kota` VALUES ('6201', '62', 'KABUPATEN KOTAWARINGIN BARAT');
INSERT INTO `tb_kota` VALUES ('6202', '62', 'KABUPATEN KOTAWARINGIN TIMUR');
INSERT INTO `tb_kota` VALUES ('6203', '62', 'KABUPATEN KAPUAS');
INSERT INTO `tb_kota` VALUES ('6204', '62', 'KABUPATEN BARITO SELATAN');
INSERT INTO `tb_kota` VALUES ('6205', '62', 'KABUPATEN BARITO UTARA');
INSERT INTO `tb_kota` VALUES ('6206', '62', 'KABUPATEN SUKAMARA');
INSERT INTO `tb_kota` VALUES ('6207', '62', 'KABUPATEN LAMANDAU');
INSERT INTO `tb_kota` VALUES ('6208', '62', 'KABUPATEN SERUYAN');
INSERT INTO `tb_kota` VALUES ('6209', '62', 'KABUPATEN KATINGAN');
INSERT INTO `tb_kota` VALUES ('6210', '62', 'KABUPATEN PULANG PISAU');
INSERT INTO `tb_kota` VALUES ('6211', '62', 'KABUPATEN GUNUNG MAS');
INSERT INTO `tb_kota` VALUES ('6212', '62', 'KABUPATEN BARITO TIMUR');
INSERT INTO `tb_kota` VALUES ('6213', '62', 'KABUPATEN MURUNG RAYA');
INSERT INTO `tb_kota` VALUES ('6271', '62', 'KOTA PALANGKA RAYA');
INSERT INTO `tb_kota` VALUES ('6301', '63', 'KABUPATEN TANAH LAUT');
INSERT INTO `tb_kota` VALUES ('6302', '63', 'KABUPATEN KOTA BARU');
INSERT INTO `tb_kota` VALUES ('6303', '63', 'KABUPATEN BANJAR');
INSERT INTO `tb_kota` VALUES ('6304', '63', 'KABUPATEN BARITO KUALA');
INSERT INTO `tb_kota` VALUES ('6305', '63', 'KABUPATEN TAPIN');
INSERT INTO `tb_kota` VALUES ('6306', '63', 'KABUPATEN HULU SUNGAI SELATAN');
INSERT INTO `tb_kota` VALUES ('6307', '63', 'KABUPATEN HULU SUNGAI TENGAH');
INSERT INTO `tb_kota` VALUES ('6308', '63', 'KABUPATEN HULU SUNGAI UTARA');
INSERT INTO `tb_kota` VALUES ('6309', '63', 'KABUPATEN TABALONG');
INSERT INTO `tb_kota` VALUES ('6310', '63', 'KABUPATEN TANAH BUMBU');
INSERT INTO `tb_kota` VALUES ('6311', '63', 'KABUPATEN BALANGAN');
INSERT INTO `tb_kota` VALUES ('6371', '63', 'KOTA BANJARMASIN');
INSERT INTO `tb_kota` VALUES ('6372', '63', 'KOTA BANJAR BARU');
INSERT INTO `tb_kota` VALUES ('6401', '64', 'KABUPATEN PASER');
INSERT INTO `tb_kota` VALUES ('6402', '64', 'KABUPATEN KUTAI BARAT');
INSERT INTO `tb_kota` VALUES ('6403', '64', 'KABUPATEN KUTAI KARTANEGARA');
INSERT INTO `tb_kota` VALUES ('6404', '64', 'KABUPATEN KUTAI TIMUR');
INSERT INTO `tb_kota` VALUES ('6405', '64', 'KABUPATEN BERAU');
INSERT INTO `tb_kota` VALUES ('6409', '64', 'KABUPATEN PENAJAM PASER UTARA');
INSERT INTO `tb_kota` VALUES ('6411', '64', 'KABUPATEN MAHAKAM HULU');
INSERT INTO `tb_kota` VALUES ('6471', '64', 'KOTA BALIKPAPAN');
INSERT INTO `tb_kota` VALUES ('6472', '64', 'KOTA SAMARINDA');
INSERT INTO `tb_kota` VALUES ('6474', '64', 'KOTA BONTANG');
INSERT INTO `tb_kota` VALUES ('6501', '65', 'KABUPATEN MALINAU');
INSERT INTO `tb_kota` VALUES ('6502', '65', 'KABUPATEN BULUNGAN');
INSERT INTO `tb_kota` VALUES ('6503', '65', 'KABUPATEN TANA TIDUNG');
INSERT INTO `tb_kota` VALUES ('6504', '65', 'KABUPATEN NUNUKAN');
INSERT INTO `tb_kota` VALUES ('6571', '65', 'KOTA TARAKAN');
INSERT INTO `tb_kota` VALUES ('7101', '71', 'KABUPATEN BOLAANG MONGONDOW');
INSERT INTO `tb_kota` VALUES ('7102', '71', 'KABUPATEN MINAHASA');
INSERT INTO `tb_kota` VALUES ('7103', '71', 'KABUPATEN KEPULAUAN SANGIHE');
INSERT INTO `tb_kota` VALUES ('7104', '71', 'KABUPATEN KEPULAUAN TALAUD');
INSERT INTO `tb_kota` VALUES ('7105', '71', 'KABUPATEN MINAHASA SELATAN');
INSERT INTO `tb_kota` VALUES ('7106', '71', 'KABUPATEN MINAHASA UTARA');
INSERT INTO `tb_kota` VALUES ('7107', '71', 'KABUPATEN BOLAANG MONGONDOW UTARA');
INSERT INTO `tb_kota` VALUES ('7108', '71', 'KABUPATEN SIAU TAGULANDANG BIARO');
INSERT INTO `tb_kota` VALUES ('7109', '71', 'KABUPATEN MINAHASA TENGGARA');
INSERT INTO `tb_kota` VALUES ('7110', '71', 'KABUPATEN BOLAANG MONGONDOW SELATAN');
INSERT INTO `tb_kota` VALUES ('7111', '71', 'KABUPATEN BOLAANG MONGONDOW TIMUR');
INSERT INTO `tb_kota` VALUES ('7171', '71', 'KOTA MANADO');
INSERT INTO `tb_kota` VALUES ('7172', '71', 'KOTA BITUNG');
INSERT INTO `tb_kota` VALUES ('7173', '71', 'KOTA TOMOHON');
INSERT INTO `tb_kota` VALUES ('7174', '71', 'KOTA KOTAMOBAGU');
INSERT INTO `tb_kota` VALUES ('7201', '72', 'KABUPATEN BANGGAI KEPULAUAN');
INSERT INTO `tb_kota` VALUES ('7202', '72', 'KABUPATEN BANGGAI');
INSERT INTO `tb_kota` VALUES ('7203', '72', 'KABUPATEN MOROWALI');
INSERT INTO `tb_kota` VALUES ('7204', '72', 'KABUPATEN POSO');
INSERT INTO `tb_kota` VALUES ('7205', '72', 'KABUPATEN DONGGALA');
INSERT INTO `tb_kota` VALUES ('7206', '72', 'KABUPATEN TOLI-TOLI');
INSERT INTO `tb_kota` VALUES ('7207', '72', 'KABUPATEN BUOL');
INSERT INTO `tb_kota` VALUES ('7208', '72', 'KABUPATEN PARIGI MOUTONG');
INSERT INTO `tb_kota` VALUES ('7209', '72', 'KABUPATEN TOJO UNA-UNA');
INSERT INTO `tb_kota` VALUES ('7210', '72', 'KABUPATEN SIGI');
INSERT INTO `tb_kota` VALUES ('7211', '72', 'KABUPATEN BANGGAI LAUT');
INSERT INTO `tb_kota` VALUES ('7212', '72', 'KABUPATEN MOROWALI UTARA');
INSERT INTO `tb_kota` VALUES ('7271', '72', 'KOTA PALU');
INSERT INTO `tb_kota` VALUES ('7301', '73', 'KABUPATEN KEPULAUAN SELAYAR');
INSERT INTO `tb_kota` VALUES ('7302', '73', 'KABUPATEN BULUKUMBA');
INSERT INTO `tb_kota` VALUES ('7303', '73', 'KABUPATEN BANTAENG');
INSERT INTO `tb_kota` VALUES ('7304', '73', 'KABUPATEN JENEPONTO');
INSERT INTO `tb_kota` VALUES ('7305', '73', 'KABUPATEN TAKALAR');
INSERT INTO `tb_kota` VALUES ('7306', '73', 'KABUPATEN GOWA');
INSERT INTO `tb_kota` VALUES ('7307', '73', 'KABUPATEN SINJAI');
INSERT INTO `tb_kota` VALUES ('7308', '73', 'KABUPATEN MAROS');
INSERT INTO `tb_kota` VALUES ('7309', '73', 'KABUPATEN PANGKAJENE DAN KEPULAUAN');
INSERT INTO `tb_kota` VALUES ('7310', '73', 'KABUPATEN BARRU');
INSERT INTO `tb_kota` VALUES ('7311', '73', 'KABUPATEN BONE');
INSERT INTO `tb_kota` VALUES ('7312', '73', 'KABUPATEN SOPPENG');
INSERT INTO `tb_kota` VALUES ('7313', '73', 'KABUPATEN WAJO');
INSERT INTO `tb_kota` VALUES ('7314', '73', 'KABUPATEN SIDENRENG RAPPANG');
INSERT INTO `tb_kota` VALUES ('7315', '73', 'KABUPATEN PINRANG');
INSERT INTO `tb_kota` VALUES ('7316', '73', 'KABUPATEN ENREKANG');
INSERT INTO `tb_kota` VALUES ('7317', '73', 'KABUPATEN LUWU');
INSERT INTO `tb_kota` VALUES ('7318', '73', 'KABUPATEN TANA TORAJA');
INSERT INTO `tb_kota` VALUES ('7322', '73', 'KABUPATEN LUWU UTARA');
INSERT INTO `tb_kota` VALUES ('7325', '73', 'KABUPATEN LUWU TIMUR');
INSERT INTO `tb_kota` VALUES ('7326', '73', 'KABUPATEN TORAJA UTARA');
INSERT INTO `tb_kota` VALUES ('7371', '73', 'KOTA MAKASSAR');
INSERT INTO `tb_kota` VALUES ('7372', '73', 'KOTA PAREPARE');
INSERT INTO `tb_kota` VALUES ('7373', '73', 'KOTA PALOPO');
INSERT INTO `tb_kota` VALUES ('7401', '74', 'KABUPATEN BUTON');
INSERT INTO `tb_kota` VALUES ('7402', '74', 'KABUPATEN MUNA');
INSERT INTO `tb_kota` VALUES ('7403', '74', 'KABUPATEN KONAWE');
INSERT INTO `tb_kota` VALUES ('7404', '74', 'KABUPATEN KOLAKA');
INSERT INTO `tb_kota` VALUES ('7405', '74', 'KABUPATEN KONAWE SELATAN');
INSERT INTO `tb_kota` VALUES ('7406', '74', 'KABUPATEN BOMBANA');
INSERT INTO `tb_kota` VALUES ('7407', '74', 'KABUPATEN WAKATOBI');
INSERT INTO `tb_kota` VALUES ('7408', '74', 'KABUPATEN KOLAKA UTARA');
INSERT INTO `tb_kota` VALUES ('7409', '74', 'KABUPATEN BUTON UTARA');
INSERT INTO `tb_kota` VALUES ('7410', '74', 'KABUPATEN KONAWE UTARA');
INSERT INTO `tb_kota` VALUES ('7411', '74', 'KABUPATEN KOLAKA TIMUR');
INSERT INTO `tb_kota` VALUES ('7412', '74', 'KABUPATEN KONAWE KEPULAUAN');
INSERT INTO `tb_kota` VALUES ('7413', '74', 'KABUPATEN MUNA BARAT');
INSERT INTO `tb_kota` VALUES ('7414', '74', 'KABUPATEN BUTON TENGAH');
INSERT INTO `tb_kota` VALUES ('7415', '74', 'KABUPATEN BUTON SELATAN');
INSERT INTO `tb_kota` VALUES ('7471', '74', 'KOTA KENDARI');
INSERT INTO `tb_kota` VALUES ('7472', '74', 'KOTA BAUBAU');
INSERT INTO `tb_kota` VALUES ('7501', '75', 'KABUPATEN BOALEMO');
INSERT INTO `tb_kota` VALUES ('7502', '75', 'KABUPATEN GORONTALO');
INSERT INTO `tb_kota` VALUES ('7503', '75', 'KABUPATEN POHUWATO');
INSERT INTO `tb_kota` VALUES ('7504', '75', 'KABUPATEN BONE BOLANGO');
INSERT INTO `tb_kota` VALUES ('7505', '75', 'KABUPATEN GORONTALO UTARA');
INSERT INTO `tb_kota` VALUES ('7571', '75', 'KOTA GORONTALO');
INSERT INTO `tb_kota` VALUES ('7601', '76', 'KABUPATEN MAJENE');
INSERT INTO `tb_kota` VALUES ('7602', '76', 'KABUPATEN POLEWALI MANDAR');
INSERT INTO `tb_kota` VALUES ('7603', '76', 'KABUPATEN MAMASA');
INSERT INTO `tb_kota` VALUES ('7604', '76', 'KABUPATEN MAMUJU');
INSERT INTO `tb_kota` VALUES ('7605', '76', 'KABUPATEN MAMUJU UTARA');
INSERT INTO `tb_kota` VALUES ('7606', '76', 'KABUPATEN MAMUJU TENGAH');
INSERT INTO `tb_kota` VALUES ('8101', '81', 'KABUPATEN MALUKU TENGGARA BARAT');
INSERT INTO `tb_kota` VALUES ('8102', '81', 'KABUPATEN MALUKU TENGGARA');
INSERT INTO `tb_kota` VALUES ('8103', '81', 'KABUPATEN MALUKU TENGAH');
INSERT INTO `tb_kota` VALUES ('8104', '81', 'KABUPATEN BURU');
INSERT INTO `tb_kota` VALUES ('8105', '81', 'KABUPATEN KEPULAUAN ARU');
INSERT INTO `tb_kota` VALUES ('8106', '81', 'KABUPATEN SERAM BAGIAN BARAT');
INSERT INTO `tb_kota` VALUES ('8107', '81', 'KABUPATEN SERAM BAGIAN TIMUR');
INSERT INTO `tb_kota` VALUES ('8108', '81', 'KABUPATEN MALUKU BARAT DAYA');
INSERT INTO `tb_kota` VALUES ('8109', '81', 'KABUPATEN BURU SELATAN');
INSERT INTO `tb_kota` VALUES ('8171', '81', 'KOTA AMBON');
INSERT INTO `tb_kota` VALUES ('8172', '81', 'KOTA TUAL');
INSERT INTO `tb_kota` VALUES ('8201', '82', 'KABUPATEN HALMAHERA BARAT');
INSERT INTO `tb_kota` VALUES ('8202', '82', 'KABUPATEN HALMAHERA TENGAH');
INSERT INTO `tb_kota` VALUES ('8203', '82', 'KABUPATEN KEPULAUAN SULA');
INSERT INTO `tb_kota` VALUES ('8204', '82', 'KABUPATEN HALMAHERA SELATAN');
INSERT INTO `tb_kota` VALUES ('8205', '82', 'KABUPATEN HALMAHERA UTARA');
INSERT INTO `tb_kota` VALUES ('8206', '82', 'KABUPATEN HALMAHERA TIMUR');
INSERT INTO `tb_kota` VALUES ('8207', '82', 'KABUPATEN PULAU MOROTAI');
INSERT INTO `tb_kota` VALUES ('8208', '82', 'KABUPATEN PULAU TALIABU');
INSERT INTO `tb_kota` VALUES ('8271', '82', 'KOTA TERNATE');
INSERT INTO `tb_kota` VALUES ('8272', '82', 'KOTA TIDORE KEPULAUAN');
INSERT INTO `tb_kota` VALUES ('9101', '91', 'KABUPATEN FAKFAK');
INSERT INTO `tb_kota` VALUES ('9102', '91', 'KABUPATEN KAIMANA');
INSERT INTO `tb_kota` VALUES ('9103', '91', 'KABUPATEN TELUK WONDAMA');
INSERT INTO `tb_kota` VALUES ('9104', '91', 'KABUPATEN TELUK BINTUNI');
INSERT INTO `tb_kota` VALUES ('9105', '91', 'KABUPATEN MANOKWARI');
INSERT INTO `tb_kota` VALUES ('9106', '91', 'KABUPATEN SORONG SELATAN');
INSERT INTO `tb_kota` VALUES ('9107', '91', 'KABUPATEN SORONG');
INSERT INTO `tb_kota` VALUES ('9108', '91', 'KABUPATEN RAJA AMPAT');
INSERT INTO `tb_kota` VALUES ('9109', '91', 'KABUPATEN TAMBRAUW');
INSERT INTO `tb_kota` VALUES ('9110', '91', 'KABUPATEN MAYBRAT');
INSERT INTO `tb_kota` VALUES ('9111', '91', 'KABUPATEN MANOKWARI SELATAN');
INSERT INTO `tb_kota` VALUES ('9112', '91', 'KABUPATEN PEGUNUNGAN ARFAK');
INSERT INTO `tb_kota` VALUES ('9171', '91', 'KOTA SORONG');
INSERT INTO `tb_kota` VALUES ('9401', '94', 'KABUPATEN MERAUKE');
INSERT INTO `tb_kota` VALUES ('9402', '94', 'KABUPATEN JAYAWIJAYA');
INSERT INTO `tb_kota` VALUES ('9403', '94', 'KABUPATEN JAYAPURA');
INSERT INTO `tb_kota` VALUES ('9404', '94', 'KABUPATEN NABIRE');
INSERT INTO `tb_kota` VALUES ('9408', '94', 'KABUPATEN KEPULAUAN YAPEN');
INSERT INTO `tb_kota` VALUES ('9409', '94', 'KABUPATEN BIAK NUMFOR');
INSERT INTO `tb_kota` VALUES ('9410', '94', 'KABUPATEN PANIAI');
INSERT INTO `tb_kota` VALUES ('9411', '94', 'KABUPATEN PUNCAK JAYA');
INSERT INTO `tb_kota` VALUES ('9412', '94', 'KABUPATEN MIMIKA');
INSERT INTO `tb_kota` VALUES ('9413', '94', 'KABUPATEN BOVEN DIGOEL');
INSERT INTO `tb_kota` VALUES ('9414', '94', 'KABUPATEN MAPPI');
INSERT INTO `tb_kota` VALUES ('9415', '94', 'KABUPATEN ASMAT');
INSERT INTO `tb_kota` VALUES ('9416', '94', 'KABUPATEN YAHUKIMO');
INSERT INTO `tb_kota` VALUES ('9417', '94', 'KABUPATEN PEGUNUNGAN BINTANG');
INSERT INTO `tb_kota` VALUES ('9418', '94', 'KABUPATEN TOLIKARA');
INSERT INTO `tb_kota` VALUES ('9419', '94', 'KABUPATEN SARMI');
INSERT INTO `tb_kota` VALUES ('9420', '94', 'KABUPATEN KEEROM');
INSERT INTO `tb_kota` VALUES ('9426', '94', 'KABUPATEN WAROPEN');
INSERT INTO `tb_kota` VALUES ('9427', '94', 'KABUPATEN SUPIORI');
INSERT INTO `tb_kota` VALUES ('9428', '94', 'KABUPATEN MAMBERAMO RAYA');
INSERT INTO `tb_kota` VALUES ('9429', '94', 'KABUPATEN NDUGA');
INSERT INTO `tb_kota` VALUES ('9430', '94', 'KABUPATEN LANNY JAYA');
INSERT INTO `tb_kota` VALUES ('9431', '94', 'KABUPATEN MAMBERAMO TENGAH');
INSERT INTO `tb_kota` VALUES ('9432', '94', 'KABUPATEN YALIMO');
INSERT INTO `tb_kota` VALUES ('9433', '94', 'KABUPATEN PUNCAK');
INSERT INTO `tb_kota` VALUES ('9434', '94', 'KABUPATEN DOGIYAI');
INSERT INTO `tb_kota` VALUES ('9435', '94', 'KABUPATEN INTAN JAYA');
INSERT INTO `tb_kota` VALUES ('9436', '94', 'KABUPATEN DEIYAI');
INSERT INTO `tb_kota` VALUES ('9471', '94', 'KOTA JAYAPURA');

-- ----------------------------
-- Table structure for tb_margin
-- ----------------------------
DROP TABLE IF EXISTS `tb_margin`;
CREATE TABLE `tb_margin`  (
  `f_id_margin` int(10) NOT NULL,
  `f_margin` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`f_id_margin`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tb_meta
-- ----------------------------
DROP TABLE IF EXISTS `tb_meta`;
CREATE TABLE `tb_meta`  (
  `f_id_meta` int(10) NOT NULL AUTO_INCREMENT,
  `f_meta_title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_meta_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_meta_tag` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'relasi ke tb tag ambil id tag;',
  PRIMARY KEY (`f_id_meta`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tb_properti
-- ----------------------------
DROP TABLE IF EXISTS `tb_properti`;
CREATE TABLE `tb_properti`  (
  `f_id_properti` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `f_kode_properti` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_nama_properti` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_desc_properti` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `f_short_desc_properti` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_tipe_properti` int(10) NULL DEFAULT NULL COMMENT 'relasi ke tb tipe;',
  `f_rate_properti` int(10) NULL DEFAULT NULL,
  `f_alamat_properti` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `f_kota_properti` int(10) NULL DEFAULT NULL COMMENT 'relasi ke tb kota;',
  `f_provinsi_properti` int(10) NULL DEFAULT NULL COMMENT 'relasi ke tb provinsi;',
  `f_durasi_properti` int(10) NULL DEFAULT NULL,
  `f_harga_properti` int(10) NULL DEFAULT NULL,
  `f_telepon_properti` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_check_in_properti` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_check_out_properti` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_pembatalan_properti` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `f_biaya_anak` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `f_peliharaan` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `f_rating_member` int(10) NULL DEFAULT NULL,
  `f_meta_title_properti` int(10) NULL DEFAULT NULL COMMENT 'relasi ke tb id meta;',
  `f_author_properti` int(10) NULL DEFAULT NULL COMMENT 'relasi id user;',
  `f_status_properti` enum('0','1') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '1' COMMENT '0:nonaktif;1:aktif;',
  PRIMARY KEY (`f_id_properti`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tb_provinsi
-- ----------------------------
DROP TABLE IF EXISTS `tb_provinsi`;
CREATE TABLE `tb_provinsi`  (
  `f_id_provinsi` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `f_nama_provinsi` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`f_id_provinsi`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tb_provinsi
-- ----------------------------
INSERT INTO `tb_provinsi` VALUES ('11', 'ACEH');
INSERT INTO `tb_provinsi` VALUES ('12', 'SUMATERA UTARA');
INSERT INTO `tb_provinsi` VALUES ('13', 'SUMATERA BARAT');
INSERT INTO `tb_provinsi` VALUES ('14', 'RIAU');
INSERT INTO `tb_provinsi` VALUES ('15', 'JAMBI');
INSERT INTO `tb_provinsi` VALUES ('16', 'SUMATERA SELATAN');
INSERT INTO `tb_provinsi` VALUES ('17', 'BENGKULU');
INSERT INTO `tb_provinsi` VALUES ('18', 'LAMPUNG');
INSERT INTO `tb_provinsi` VALUES ('19', 'KEPULAUAN BANGKA BELITUNG');
INSERT INTO `tb_provinsi` VALUES ('21', 'KEPULAUAN RIAU');
INSERT INTO `tb_provinsi` VALUES ('31', 'DKI JAKARTA');
INSERT INTO `tb_provinsi` VALUES ('32', 'JAWA BARAT');
INSERT INTO `tb_provinsi` VALUES ('33', 'JAWA TENGAH');
INSERT INTO `tb_provinsi` VALUES ('34', 'DI YOGYAKARTA');
INSERT INTO `tb_provinsi` VALUES ('35', 'JAWA TIMUR');
INSERT INTO `tb_provinsi` VALUES ('36', 'BANTEN');
INSERT INTO `tb_provinsi` VALUES ('51', 'BALI');
INSERT INTO `tb_provinsi` VALUES ('52', 'NUSA TENGGARA BARAT');
INSERT INTO `tb_provinsi` VALUES ('53', 'NUSA TENGGARA TIMUR');
INSERT INTO `tb_provinsi` VALUES ('61', 'KALIMANTAN BARAT');
INSERT INTO `tb_provinsi` VALUES ('62', 'KALIMANTAN TENGAH');
INSERT INTO `tb_provinsi` VALUES ('63', 'KALIMANTAN SELATAN');
INSERT INTO `tb_provinsi` VALUES ('64', 'KALIMANTAN TIMUR');
INSERT INTO `tb_provinsi` VALUES ('65', 'KALIMANTAN UTARA');
INSERT INTO `tb_provinsi` VALUES ('71', 'SULAWESI UTARA');
INSERT INTO `tb_provinsi` VALUES ('72', 'SULAWESI TENGAH');
INSERT INTO `tb_provinsi` VALUES ('73', 'SULAWESI SELATAN');
INSERT INTO `tb_provinsi` VALUES ('74', 'SULAWESI TENGGARA');
INSERT INTO `tb_provinsi` VALUES ('75', 'GORONTALO');
INSERT INTO `tb_provinsi` VALUES ('76', 'SULAWESI BARAT');
INSERT INTO `tb_provinsi` VALUES ('81', 'MALUKU');
INSERT INTO `tb_provinsi` VALUES ('82', 'MALUKU UTARA');
INSERT INTO `tb_provinsi` VALUES ('91', 'PAPUA BARAT');
INSERT INTO `tb_provinsi` VALUES ('94', 'PAPUA');

-- ----------------------------
-- Table structure for tb_tag_image
-- ----------------------------
DROP TABLE IF EXISTS `tb_tag_image`;
CREATE TABLE `tb_tag_image`  (
  `f_id_tag_image` int(10) NOT NULL,
  `f_kode_image` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_tag_image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`f_id_tag_image`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tb_tag_produk
-- ----------------------------
DROP TABLE IF EXISTS `tb_tag_produk`;
CREATE TABLE `tb_tag_produk`  (
  `f_id_tag_produk` int(10) NOT NULL AUTO_INCREMENT,
  `f_parent_produk` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'relasi dengan kode properti, kode kamar, kode umrah dll;',
  `f_tag_produk` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`f_id_tag_produk`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tb_things_todo
-- ----------------------------
DROP TABLE IF EXISTS `tb_things_todo`;
CREATE TABLE `tb_things_todo`  (
  `f_id_ttd` int(10) NOT NULL AUTO_INCREMENT,
  `f_kode_ttd` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `f_nama_ttd` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_kota_ttd` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'relasi dengan tb kota;',
  `f_desc_ttd` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `f_status_ttd` enum('0','1') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '0:ga aktif,1:aktif;',
  PRIMARY KEY (`f_id_ttd`, `f_kode_ttd`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tb_tipe
-- ----------------------------
DROP TABLE IF EXISTS `tb_tipe`;
CREATE TABLE `tb_tipe`  (
  `f_id_tipe` int(10) NOT NULL AUTO_INCREMENT,
  `f_nama_tipe` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_jenis_tipe` enum('0','1','2','3','4') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '0:global;1:properti:2:pakettour;3:paketumroh;4:sewakendaraan;',
  `f_status_tipe` enum('0','1') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '0:nonaktif;1:aktif;',
  PRIMARY KEY (`f_id_tipe`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tb_tour
-- ----------------------------
DROP TABLE IF EXISTS `tb_tour`;
CREATE TABLE `tb_tour`  (
  `f_id_tour` int(10) NOT NULL,
  `f_kode_tour` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_nama_tour` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_desc_tour` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `f_short_desc_tour` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_lokasi_tour` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_durasi_tour` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`f_id_tour`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tb_tour_guide
-- ----------------------------
DROP TABLE IF EXISTS `tb_tour_guide`;
CREATE TABLE `tb_tour_guide`  (
  `f_id_tour_guide` int(10) NOT NULL AUTO_INCREMENT,
  `f_kode_tour_guide` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `f_nama_tour_guide` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_kota_tour_guide` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'relasi dengan tb kota;',
  PRIMARY KEY (`f_id_tour_guide`, `f_kode_tour_guide`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tb_umrah
-- ----------------------------
DROP TABLE IF EXISTS `tb_umrah`;
CREATE TABLE `tb_umrah`  (
  `f_id_umrah` int(10) NOT NULL,
  `f_kode_umrah` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`f_id_umrah`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tb_user_data
-- ----------------------------
DROP TABLE IF EXISTS `tb_user_data`;
CREATE TABLE `tb_user_data`  (
  `f_id` int(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `f_kode` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `f_nama` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_username` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `f_password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_telepon` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_tempat_lahir` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_tanggal_lahir` date NULL DEFAULT NULL,
  `f_alamat` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `f_kota` int(10) NULL DEFAULT NULL,
  `f_provinsi` int(10) NULL DEFAULT NULL,
  `f_gender` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `f_level` enum('1','2','3','4','5') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '0:superadmin;1:admin;2:mitra;3:member;',
  `f_status` enum('0','1','2') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '0:nonaktif;1:aktif;2:delay;',
  PRIMARY KEY (`f_id`, `f_kode`, `f_email`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
